### ISSUE TITLE
Code new record input screen and input validation (User Story #18)

### ISSUE THREAD

**Issue by taerakwon** [Team-Taera/COMP231-F2016-GROUP1#39]
#18

**Comment by RyanYizhaoHuang** [comment]
Finished.

**Comment by RyanYizhaoHuang** [comment]
Spent 0.5 hour to finished creating UI for add new record.

**Comment by RyanYizhaoHuang** [comment]
Finished add new record window.

**Comment by domlau** [comment]
@taerakwon @kkh0811 @RyanYizhaoHuang 
Cloned from branch 1.18. Re-organising code in the NewRecordForm.cs and UserNameValidator.cs.

**Comment by domlau** [comment]
@taerakwon @RyanYizhaoHuang @mekhaleganesh @kkh0811 @prtk15 

Task#39 is completed after UAT. I am going to close the issue.
