### ISSUE TITLE
Design and write SQL update query to store new record

### ISSUE THREAD

**Issue by taerakwon** [Team-Taera/COMP231-F2016-GROUP1#40]

**Comment by kkh0811** [comment]
Done

**Comment by taerakwon** [comment]
Completed Oct 27, 2016

**Comment by kkh0811** [comment]
@taerakwon 
Actual Hours: 9.5 hours
Challenge: I needed to create tables (UserAccount,UserRecord,UserRecordCategories and Categories) and connect database to C#. Had to created procedures after connection is successful. After that, tested my procedures on c#.

**Comment by taerakwon** [comment]
Merged into "Code new record input screen and input validation #39"
