### ISSUE TITLE
Create a class to store new record (User Story #18)

### ISSUE THREAD

**Issue by taerakwon** [Team-Taera/COMP231-F2016-GROUP1#41]
#18

**Comment by domlau** [comment]
Code validation to ensure user inputs correct information and does not allow any injection code inputs.

**Comment by domlau** [comment]
@taerakwon 
Reopened task to add in hours and issues with task. In total, I have spent 14.5 hours working on this task. I needed the extra hours because there were issues with how to validate properly. In addition, I also had to do some research on how to use regular expression.

**Comment by domlau** [comment]
Task completed requiring 4 extra hours in order to try and apply SOLID principles to the code.
