### ISSUE TITLE
Code detail view window and establish connection with database

### ISSUE THREAD

**Issue by taerakwon** [Team-Taera/COMP231-F2016-GROUP1#45]

**Comment by domlau** [comment]
Completed the code to view the detailed record in view window.

**Comment by taerakwon** [comment]
@domlau Does it pull all information?

**Comment by domlau** [comment]
@taerakwon Yes, it'll pull all the information that is selected from the record information. Please see pull request #75.

**Comment by taerakwon** [comment]
Pull request 75 - Completed Oct 30, 2016

**Comment by domlau** [comment]
@taerakwon 
Reopened task to add in hours and explain the task. I have spent 7 hours working on this task. It took me 4 hours to code the detail the window and 3 hours to do the testing and making sure the code does not have conflict.

**Comment by domlau** [comment]
This task is still in progress because I need to apply SOLID principles. I am going to require additional time to complete this task.

**Comment by taerakwon** [comment]
Removed
