### ISSUE TITLE
Allow user to edit details from view existing records form (User Story #28)

### ISSUE THREAD

**Issue by taerakwon** [Team-Taera/COMP231-F2016-GROUP1#46]
#28

**Comment by mekhaleganesh** [comment]
Query is done .

**Comment by mekhaleganesh** [comment]
@taerakwon 
worked for 2 hrs to figure out the query and implement it

**Comment by mekhaleganesh** [comment]
@taerakwon @domlau @RyanYizhaoHuang @kkh0811 @prtk15 
we cannot make it "ViewRecord" form editable because if make this form editable we do not have textbox to verify password.  It is better to open the editForm by clicking edit button.

**Comment by mekhaleganesh** [comment]
completed and merged to branch 1.28
tested and its working..

**Comment by domlau** [comment]
Task is completed. Closed issue.
