### ISSUE TITLE
Implementing interactions with list of record (User Story #23)

### ISSUE THREAD

**Issue by taerakwon** [Team-Taera/COMP231-F2016-GROUP1#48]
#23

**Comment by RyanYizhaoHuang** [comment]
Finished. The toolebar is hideing because of some function for the toolbar have been implemented yet.

**Comment by RyanYizhaoHuang** [comment]
Spent 1.5 hour to implement right click meun and menu.

**Comment by taerakwon** [comment]
@RyanYizhaoHuang 
In Iteration 3, this task will focus on left mouse click and right click interaction with the record (Do not need to worry about injection/copy paste as they will be done in other user story)

**Comment by taerakwon** [comment]
CLOSED AFTER EMERGENCY MEETING (NOV 30th, 2016)
