### ISSUE TITLE
INVALID TASK

### ISSUE THREAD

**Issue by taerakwon** [Team-Taera/COMP231-F2016-GROUP1#51]
#23

**Comment by RyanYizhaoHuang** [comment]
Finished.

**Comment by RyanYizhaoHuang** [comment]
Reopen to add finished time.

**Comment by RyanYizhaoHuang** [comment]
Finished the task used 2.5 hours. Took prtk15's task.

**Comment by taerakwon** [comment]
Pratik taking over, applying SOLID (Modifying existing codes and structures)

**Comment by prtk15** [comment]
Yesterday gone through the code of ryan  and i have spent about a hour. I think i will complete it by tomorrow.

**Comment by RyanYizhaoHuang** [comment]
Finished this task just used 4.5 hours.

**Comment by prtk15** [comment]
@RyanYizhaoHuang @domlau @mekhaleganesh @kkh0811 i have just committed the profile form and removed the view category option from the toolbar menu.

**Comment by taerakwon** [comment]
@prtk15 Main GUI application needs to be updated as we discussed during Release 1 presentation.
- Also, please try to pull Master branch and continue working on your branch as Master branch is far ahead of what you have at the moment (Do not want to cause major conflict)

**Comment by taerakwon** [comment]
REMOVED AFTER EMERGENCY MEETING (NOV 30th, 2016)
