### ISSUE TITLE
Code new record category popup window form (User Story #19)

### ISSUE THREAD

**Issue by taerakwon** [Team-Taera/COMP231-F2016-GROUP1#52]
#19

**Comment by RyanYizhaoHuang** [comment]
Working on it. Create the UI for add new category. Working on implementing the function.

**Comment by RyanYizhaoHuang** [comment]
Finished Code new record category popup window(#52) in three hours, use one more hours because need to search how to refresh category after added new category.

**Comment by RyanYizhaoHuang** [comment]
New Record Category popup window finished.

**Comment by RyanYizhaoHuang** [comment]
Task completed
