### ISSUE TITLE
Structure Database Schema and allow implementation by other developers

### ISSUE THREAD

**Issue by taerakwon** [Team-Taera/COMP231-F2016-GROUP1#82]

**Comment by kkh0811** [comment]
I will establish database structure

**Comment by domlau** [comment]
@taerakwon @kkh0811 @RyanYizhaoHuang @mekhaleganesh @prtk15 

Guys, I found the solution to the issue regarding to the DB when we had our SCRUM meeting on Tuesday. Please refer to this link.

https://msdn.microsoft.com/en-us/library/ms246989.aspx

**Comment by kkh0811** [comment]
Thanks
