### ISSUE TITLE
A user can edit category name (User Story #30)

### ISSUE THREAD

**Issue by taerakwon** [Team-Taera/COMP231-F2016-GROUP1#97]
#30

**Comment by RyanYizhaoHuang** [comment]
Create IUpdate interface to accept two entities(old Entity, new Entity)
Create UpdateUserRecord_UpdateCategoryHelper class to update category name to UserRecord table.
Create UpdateCategoryNameHelper class to update category name to Categories table.
Change ManupulateCategoryForm so it can be use for add and edit user stroies
Add Event handler to EditCategory button in mainForm.
This Task is ready for testing.

**Comment by RyanYizhaoHuang** [comment]
Completed.
